//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://flights.com")]
[System.Xml.Serialization.XmlRootAttribute("user", Namespace="http://flights.com", IsNullable=false)]
public partial class user : entity {
    
    private string nameField;
    
    private string surnameField;
    
    private string middleNameField;
    
    private string phoneField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", ElementName = "surname")]
    public string surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    [XmlElementAttribute()]
    public string middleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    public override string ToString()
    {
        return $"\nUserID: {id}, Name: {nameField}, Surname: {surname}, MiddleName {middleName}, Phone: {phone}";
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://flights.com")]
[System.Xml.Serialization.XmlRootAttribute("user", Namespace="http://flights.com", IsNullable=false)]
public partial class entity {
    
    private ulong idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://flights.com")]
[System.Xml.Serialization.XmlRootAttribute("flight", Namespace="http://flights.com", IsNullable=false)]
public partial class Flight : entity {
    
    private string startField;
    
    private string destinationField;
    
    private System.DateTime departureTimeField;
    
    private System.DateTime arrivalTimeField;
    
    private double costField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime departureTime {
        get {
            return this.departureTimeField;
        }
        set {
            this.departureTimeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime arrivalTime {
        get {
            return this.arrivalTimeField;
        }
        set {
            this.arrivalTimeField = value;
        }
    }
    
    /// <remarks/>
    public double cost {
        get {
            return this.costField;
        }
        set {
            this.costField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://flights.com")]
[System.Xml.Serialization.XmlRootAttribute("ticket", Namespace="http://flights.com", IsNullable=false)]
public partial class Ticket : entity {
    
    private ulong userIdField;
    
    private ulong bookingIdField;
    
    private byte lineField;
    
    private byte seatField;
    
    /// <remarks/>
    public ulong userId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    public ulong bookingId {
        get {
            return this.bookingIdField;
        }
        set {
            this.bookingIdField = value;
        }
    }
    
    /// <remarks/>
    public byte line {
        get {
            return this.lineField;
        }
        set {
            this.lineField = value;
        }
    }
    
    /// <remarks/>
    public byte seat {
        get {
            return this.seatField;
        }
        set {
            this.seatField = value;
        }
    }
    
    public override string ToString()
    {
        return $"TicketID: {id}, UserID: {userId}, BookingID: {bookingId}, Line: {line}, Seat {seat}";
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://flights.com")]
[System.Xml.Serialization.XmlRootAttribute("booking", Namespace="http://flights.com", IsNullable=false)]
public partial class Booking : entity {
    
    private ulong flightIdField;
    
    private BookingStatus bookingStatusField;
    
    private List<Ticket> _ticketsField;
    
    public ulong flightId {
        get {
            return this.flightIdField;
        }
        set {
            this.flightIdField = value;
        }
    }
    
    public BookingStatus bookingStatus {
        get {
            return this.bookingStatusField;
        }
        set {
            this.bookingStatusField = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("ticket")]
    public List<Ticket> tickets {
        get {
            return this._ticketsField ??= new List<Ticket>();
        }
        set {
            this._ticketsField = value;
        }
    }
    
    public override string ToString()
    {
        var info = "\nBooking Entity";
        info =  info + $"\nBookingID: {id}, BookingStatus: {bookingStatus}, FlightID: {flightId}";

        info = info + "\nTickets ->";
        
        foreach (var ticket in tickets)
        {
            info = info + "\n\t" + ticket.ToString() + ',';
        }

        return info;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://flights.com")]
public enum BookingStatus {
    
    /// <remarks/>
    New,
    
    /// <remarks/>
    Active,
    
    /// <remarks/>
    Finished,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://flights.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://flights.com", IsNullable=false)]
public partial class bookings {
    
    private Booking[] bookingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("booking")]
    public Booking[] booking {
        get {
            return this.bookingField;
        }
        set {
            this.bookingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://flights.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://flights.com", IsNullable=false)]
public partial class flights {
    
    private Flight[] flightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("flight")]
    public Flight[] flight {
        get {
            return this.flightField;
        }
        set {
            this.flightField = value;
        }
    }
}
